module.exports.formatFieldToName = ({
    field1,
    field2,
    field4,
    field5,
    field6,
    field7,
    field8,
    field9,
    field10,
    field12,
    field15,
    field19,
    field20,
    field22,
    field28,
    field31,
    field32,
    type,
}) => ({
    record_id: field20,
    account: field22,
    firstName: field1,
    lastName: field2,
    fullname: field4,
    areaCode: field5,
    threeDigit: field6,
    fourDigit: field7,
    phone: field8,
    memberSince: field10,
    renew: field28,
    prev: field31,
    buy: field19,
    remain: field12,
    fee: field9,
    invoiceDate: field15,
    invoiceTime: field32,
    type,
});
