module.exports = {
    channels: {
        LOGIN: 'LOGIN',
        SENTER_FIND_PHONE: 'SENTER_FIND_PHONE',
        SENTER_FIND_ACCOUNT: 'SENTER_FIND_ACCOUNT',
        SENTER_FIND_FIRST_NAME: 'SENTER_FIND_FIRST_NAME',
        SENTER_FIND_LAST_NAME: 'SENTER_FIND_LAST_NAME',
        SENTER_FIND_BOTH_NAME: 'SENTER_FIND_BOTH_NAME',
        SENTER_REPORT: 'SENTER_REPORT',
        SENTER_ADD: 'SENTER_ADD',
        SENTER_BUY: 'SENTER_BUY',
        SENTER_PRINT: 'SENTER_PRINT',
        SENTER_ACCOUNT_HISTORY: 'SENTER_ACCOUNT_HISTORY',
        SENTER_BACKUP: 'SENTER_BACKUP',
        SENTER_EDIT: 'SENTER_EDIT',
        SENTER_DELETE: 'SENTER_DELETE',
        SENTER_CLOSE: 'SENTER_CLOSE',
    },
};
