module.exports = {
    channels: {
        APP_INFO: 'APP_INFO',
        LOGIN: 'LOGIN',
        LOGOUT: 'LOGOUT',
        FIND: 'FIND',
        BUY: 'BUY',
        EDIT: 'EDIT',
        RENEW: 'RENEW',
        ADD: 'ADD',
        HISTORY: 'HISTORY',
        TOTAL: 'TOTAL',
        LAST_RECORD: 'LAST_RECORD',
        TOTAL_FEE: 'TOTAL_FEE',
        TOTAL_BUY: 'TOTAL_BUY',
        TOTAL_RENEW: 'TOTAL_RENEW',
        REPORT: 'REPORT',
        CLOSE_APP: 'CLOSE_APP',
        BACKUP: 'BACKUP',
        SHOW_BACKUP_DIALOG: 'SHOW_BACKUP_DIALOG',
        PRINT_RECEIPT: 'PRINT_RECEIPT',
        PRINT_BUY_RECEIPT: 'PRINT_BUY_RECEIPT',
        PRINT_RENEW_RECEIPT: 'PRINT_RENEW_RECEIPT',
        HISTORY_REPORT: 'HISTORY_REPORT',
        DELETE_ACCOUNT: 'DELETE_ACCOUNT',
        GET_USERS: 'GET_USERS',
        ADD_USER: 'ADD_USER',
        DELETE_USER: 'DELETE_USER',
        EDIT_USER: 'EDIT_USER',
    },
};
